[theme]
base = "light"
primaryColor = "#6456E8"
backgroundColor = "#F7F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#192236"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
